- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repositories
    packages:
      update_cache: yes
      change_when: False

  tasks:
    - include: tasks/packages.yml