- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: true
        allow_unauthenticated: true
        change_when: false
        upgrade: "full"

  tasks:
    - include: tasks/packages.yml