- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: update repositories
    apt:
      update_cache: yes
      change_when: allow_unauthenticated

  tasks:
    - include: tasks/packages.yml