- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
        allow_unauthenticated: yes
        change_when: False

  tasks:
    - include: tasks/packages.yml