- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      ansible.builtin.apt:
        name: "*"
        state: latest 

  tasks:
    - include: tasks/packages.yml